import React,{useState} from 'react';
import {View,Text,SafeAreaView,ScrollView,TouchableOpacity,TextInput} from 'react-native';
import MarqueeText from 'react-native-marquee';
import LogH from '../assets/loginww.svg';
//import MaterialIcons from 'react-native-vector-icons/MaterialIcons';
import WebView from 'react-native-webview';
import { Paragraph } from 'react-native-paper';
const TermsNconditions = ({}) => {
    
    
    return(
        
        <ScrollView> 

            <Text>

            </Text>
        <Paragraph>


PLEASE READ THESE TERMS OF USE CAREFULLY. BY CONTINUING TO ACCESS AND USE THIS APPLICATION YOU CONFIRM THAT YOU ACCEPT OUR TERMS AND CONDITIONS DESCRIBED HEREIN. IF YOU DO NOT AGREE THE TERMS OF USE, DO NOT USE THIS APPLICATION.

Welcome to SugamAyur mobile Application (defined hereunder). The Application is operated by Novocura Tech Health Services Private Limited (“NTHS”), having its registered office at 1245, 22nd Main Road, 13th Cross Rd, 1st Sector, HSR Layout, Bengaluru, Karnataka 560102.

The terms “You” or “Your” refer to you as the user (irrespective of whether You are a Registered User (defined hereunder), HSP Registered User (defined hereunder) or a Non-Registered User (defined hereunder)) and the terms “NTHS”, “We”, “Us”, “Company”, “Our” and/or “mfine” refer to NTHS. In the event the Application is being used by a person on your behalf, the expression “You” or “Your” or the “User” shall apply to such person as well.

These Terms of Use, Privacy Policy, together with any additional Service specific terms and conditions, other policies which may be applicable to specific portions of the Application and any disclaimers which may be present on the Application are jointly referred to as “Agreement” and constitute the terms of Your access and use of the Application and the Services (defined hereunder). Where any part of the Agreement is modified in accordance with the terms of the Agreement, the Agreement shall be enforceable in its modified form.

The Agreement supersedes all previous oral and written terms and conditions (if any) communicated to You.

THE APPLICATION

NTHS is the author and publisher of the Application, which shall mean the mobile application, website, blog contained therein, queries answered by Our team over email, phone or any other medium and all variants, tools, editions, add-ons, and ancillary products or services of the Application (including all files and images contained therein or generated by the software, and accompanying data, herein referred to individually or collectively as “Application”). The Application may be used by Users (defined below) to avail Services and/or to find, access, manage and organize information including but not limited to personal or non-personal information, doctor/consultant information, appointments, prescriptions, laboratory and diagnostic tests, drug delivery, electronic medical records, billing, inventory, accounting details and other relevant information.

The Application titled ‘Self-Assessment Tool’ is purely for informational and educational purposes and is not intended to provide or be used for the diagnosis or treatment of disease or other conditions, including COVID-19. The guidance you receive depends on the accuracy of the information you provide as well as current guidelines for responding to symptoms associated with the novel coronavirus COVID-19.

USERS

“Registered Users” are users:

who have successfully registered themselves with NTHS through the Application by providing information that is true and accurate, and who can log on to their account on the Application by providing their username and password (“Primary User”); or
whose profile has successfully been created on the Application under the account of a Primary User, by providing information that is true and accurate (“Secondary User”).
“Healthcare Service Providers” or “HSPs” are third parties including but not limited to clinic or hospital listed on the Application, also, includes their duly qualified doctors, nurses, paramedical staff, physiotherapists, consultants, medical equipment suppliers, laboratory service providers, phlebotomist, pharmacist other incidental and ancillary healthcare service providers listed on the Application and who interacts with Users as part of the Services.

“HSP Registered Users” are Registered Users whose profile has a unique identification attached to it including but not limited to UHID (unique health identification) or UMR (unique medical record). HSP Registered Users may not be permitted to access to certain areas of the Application.

“Non-Registered Users” are users who have not registered themselves on the Application. Non-Registered Users may not be provided access to certain areas of the Application.

Registered Users, HSP Registered Users and Non-Registered Users shall individually or collectively be referred to as “Users”.

ACCESS AND USAGE RIGHTS OF USERS

Non - Registered User: A Non - Registered User is not permitted to access or make use of the Application for any purpose other than the following permitted use:

To browse the Application without accessing any Services;
To use Self-Assessment Tool;
To share the Application via social media applications.
HSP Registered Users: A HSP Registered User is only permitted to access and use the Services provided through a particular HSP only or any other limitations and restrictions as are prescribed under the Agreement or may be otherwise communicated to HSP Registered User from time to time through any contact information shared by HSP or HSP Registered User at the time of registration.

Registered User: A Registered User is specifically permitted to:

Enjoy all the access and usage rights of a Non-Registered User;
Access and use the Services subject to such limitations and restrictions as are prescribed under the Agreement or may be otherwise communicated to Registered User from time to time through any contact information shared by such user at the time of registration.
CONTENT

The data and information available on the Application may be categorized as follows:

Data and information generated or provided by Unregistered Users, HSP Registered Users and Registered Users on the Application (“User Content”).
Data and information which NTHS (through itself or its contractors) has generated or procured for the Application and includes data and information generated or provided by HSP (“NTHS Content”).
GENERAL TERMS OF USE

As required by law, You must be at least 18 years of age or older, have a sound mind and not debarred by any law to contract in order to access and use the Application and Services as a Primary User. In case the Application or Services are to be accessed or used by a minor (i.e. a person less than 18 years of age), then only the legal guardian/representative of such person shall register himself/herself as a Primary User and create/add the profile of the minor as a Secondary User. 

All Services will be requested for, and provided to, the Primary User only. A Secondary User may avail the Services rendered to the Primary User only as a beneficiary. The Primary User will be entirely responsible and accountable for the Secondary User’s activity on the Application, as if the Application and Services were being accessed and used by the Primary User. However, this shall not discharge the Secondary User who is adult and of sound mind from liability towards NTHS or its contractors or agents and NTHS shall have the right to proceed against Secondary User and Primary User, either jointly or severally, for acts and omissions of Secondary User that violate the Agreement.

You will use the Application and the features provided on the Application only in relation to and in compliance with all applicable Indian laws. You will not use this Application, or any feature provided on the Application for any purposes not intended under this Agreement.

You should limit the use of this Application to India only. We are not responsible if You avail any Service from outside India. You must have the advice and/or prescription given by such HSP validated by a local registered medical practitioner.

Certain Services are location specific. Depending on Your location certain Services may not be available to You.

You will not deliberately use the Application in any way that is unlawful or harms NTHS, its directors, employees, affiliates, distributors, partners, service providers and/or any User and/or data or content on the Application.

You will not use the Application for any illegal, immoral, offensive purpose or for any other purpose that may infringe or violate any applicable laws and regulations.

You will not interfere, disrupt or hamper with the proper functioning of the Application.

As a User, You may have access to business sensitive information. You shall not share such information with NTHS’s direct competitors or use it for competitive purposes, except with NTHS’s prior written consent.

You understand that as part of Your registration process as well as in course of Your use of the Application, You may receive communication from NTHS on Your registered contact information. These communications will relate to Your registration, Services provided by NTHS, transactions that You carry out through the Application and any such information found suitable of Your attention by NTHS. Please note that NTHS will send these communications only to the contact details that You or HSP provide on the Application. It is Your responsibility to ensure that You provide the correct contact details for the transaction You wish to enter. Further, NTHS may also send notifications and reminders to You for the features that You may be using on the Application. By accepting these Terms of Use You provide Us Your consent to collect Your medical records and/or reports from HSP. NTHS may also share the dynamic password with You in order to facilitate the online delivery of your medical report. You hereby consent to receive such communications from NTHS.

You will not share Your log-in details with anyone. You are responsible for maintaining the confidentiality of Your account access information and password. You shall be responsible for all usage of Your account and password, whether or not authorized by You. You shall immediately notify NTHS of any actual or suspected unauthorized use of the Your account or password. NTHS will not be liable for Your losses caused by any unauthorized use of Your account. You may be liable for the losses of NTHS or others due to such unauthorized use.

SERVICES

NTHS a transaction facilitator

Through the Application, NTHS facilitates the purchase of Services offered for sale by HSP. You understand and agree that NTHS merely provide hosting services to You. All Services offered for sale on the Application are owned by HSP. NTHS has no control over HSP Services and does not originate or initiate the transmission or select the sender/recipient of the transmission. The authenticity and genuineness of the Services made available by HSP through the Application shall be the sole responsibility of HSP. You understand and agree that Application shall have no liability with respect to the authenticity of the Services being facilitated through the Application.

Use of Services

The Application may be used to access a variety of healthcare and related services. Depending on the status of Your registration and subject to the limitations and restrictions imposed by the Agreement or by NTHS, You may avail following services through the Application:

Online Consultations (through mfine care team doctors and/or HSP);
Home examination;
Lab/sample collections;
Booking radiology services;
Delivery of pharmaceutical goods and services offered for sale by the HSP;
Doctor prescribed medicines/drugs delivery;
OTC drugs delivery;
Home services including but not limited to vaccination nonstress test, physiotherapy or any other therapy;
Long term care programs for chronic diseases;
Follow up service;
Post-surgery care;
Second opinion service;
Patient data storage service;
Built-in app features such as health trackers, medicine reminders, storage and display of Your medical records, information and history, including general medical information, outpatient records, discharge summaries, prescriptions, lab investigations and radiology reports along with information regarding Your family members;
Such other services as may be intimated from time to time.
The aforesaid list of services is jointly referred to as “Services.”

The Services are non-transferable and only cover the Registered User.

You agree and acknowledge that the property and title in the drugs ordered by You shall stand immediately transferred to You upon the dispensation of drugs and the raising of the invoice at the concerned HSP. Accordingly, the sale of drugs is concluded at the concerned HSP itself. Post Your acceptance of the drugs, the related Services would not be eligible for any exchange or refund.

The minimum age requirement of 18 years does not apply to any Service that is open to children and adolescents from Age 1-18.

Online Consultations



        </Paragraph>

            </ScrollView>    
            
        
    )
}
export default TermsNconditions;